// <auto-generated />
using System;
using ElaArquitetura.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ElaArquitetura.Infrastructure.Migrations
{
    [DbContext(typeof(ElaArquiteturaDbContext))]
    [Migration("20260904235222_AdicionaRefreshTokens")]
    partial class AdicionaRefreshTokens
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ElaArquitetura.Domain.Entities.ChecklistItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Concluido")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ConcluidoPor")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("EtapaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjetoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SubEtapaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EtapaId");

                    b.HasIndex("SubEtapaId");

                    b.HasIndex("ProjetoId", "EtapaId");

                    b.ToTable("checklist_itens", (string)null);
                });

            modelBuilder.Entity("ElaArquitetura.Domain.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Endereco")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Nome");

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("ElaArquitetura.Domain.Entities.Entrega", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataEnvioWhatsapp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EnviadoParaWhatsapp")
                        .HasColumnType("boolean");

                    b.Property<string>("LinkDrive")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ProjetoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjetoId");

                    b.ToTable("entregas", (string)null);
                });

            modelBuilder.Entity("ElaArquitetura.Domain.Entities.Etapa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Final")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Opcional")
                        .HasColumnType("boolean");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("etapas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Final = false,
                            Nome = "Cadastro do Cliente",
                            Opcional = false,
                            Ordem = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Final = false,
                            Nome = "Estudos Preliminares",
                            Opcional = false,
                            Ordem = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Final = false,
                            Nome = "Anteprojeto",
                            Opcional = false,
                            Ordem = 3
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            Final = false,
                            Nome = "Projeto Executivo",
                            Opcional = false,
                            Ordem = 4
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            Final = false,
                            Nome = "Relatório de Obra",
                            Opcional = true,
                            Ordem = 5
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            Final = true,
                            Nome = "Conclusão e Entrega",
                            Opcional = false,
                            Ordem = 6
                        });
                });

            modelBuilder.Entity("ElaArquitetura.Domain.Entities.Funcionario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("funcionarios", (string)null);
                });

            modelBuilder.Entity("ElaArquitetura.Domain.Entities.Projeto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EtapaAtualId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EtapaAtualId");

                    b.HasIndex("Status");

                    b.ToTable("projetos", (string)null);
                });

            modelBuilder.Entity("ElaArquitetura.Domain.Entities.ProjetoFuncionario", b =>
                {
                    b.Property<Guid>("ProjetoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FuncionarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("PapelNoProjeto")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ProjetoId", "FuncionarioId");

                    b.HasIndex("FuncionarioId");

                    b.ToTable("projeto_funcionarios", (string)null);
                });

            modelBuilder.Entity("ElaArquitetura.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiraEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FuncionarioId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Revogado")
                        .HasColumnType("boolean");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("FuncionarioId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("ElaArquitetura.Domain.Entities.SubEtapa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EtapaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EtapaId");

                    b.ToTable("sub_etapas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000101"),
                            EtapaId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Nome = "Briefing",
                            Ordem = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000102"),
                            EtapaId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Nome = "Levantamento em Locação",
                            Ordem = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000103"),
                            EtapaId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Nome = "Estudo de Layout",
                            Ordem = 3
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000201"),
                            EtapaId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Nome = "Executivo de Obra",
                            Ordem = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000202"),
                            EtapaId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Nome = "Detalhamento de Marcenaria",
                            Ordem = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000203"),
                            EtapaId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Nome = "Detalhamento de Marmoraria",
                            Ordem = 3
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000204"),
                            EtapaId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Nome = "Memoriais Descritivos",
                            Ordem = 4
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000205"),
                            EtapaId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Nome = "Imagens",
                            Ordem = 5
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000206"),
                            EtapaId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Nome = "Maquete 3D",
                            Ordem = 6
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000207"),
                            EtapaId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Nome = "Render",
                            Ordem = 7
                        });
                });

            modelBuilder.Entity("ElaArquitetura.Domain.Entities.ChecklistItem", b =>
                {
                    b.HasOne("ElaArquitetura.Domain.Entities.Etapa", null)
                        .WithMany()
                        .HasForeignKey("EtapaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ElaArquitetura.Domain.Entities.Projeto", null)
                        .WithMany()
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElaArquitetura.Domain.Entities.SubEtapa", null)
                        .WithMany()
                        .HasForeignKey("SubEtapaId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ElaArquitetura.Domain.Entities.Cliente", b =>
                {
                    b.OwnsOne("ElaArquitetura.Domain.ValueObjects.Telefone", "Telefone", b1 =>
                        {
                            b1.Property<Guid>("ClienteId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("telefone");

                            b1.HasKey("ClienteId");

                            b1.HasIndex("Numero");

                            b1.ToTable("clientes");

                            b1.WithOwner()
                                .HasForeignKey("ClienteId");
                        });

                    b.Navigation("Telefone");
                });

            modelBuilder.Entity("ElaArquitetura.Domain.Entities.Entrega", b =>
                {
                    b.HasOne("ElaArquitetura.Domain.Entities.Projeto", null)
                        .WithMany()
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ElaArquitetura.Domain.Entities.Projeto", b =>
                {
                    b.HasOne("ElaArquitetura.Domain.Entities.Cliente", null)
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ElaArquitetura.Domain.Entities.Etapa", null)
                        .WithMany()
                        .HasForeignKey("EtapaAtualId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ElaArquitetura.Domain.Entities.ProjetoFuncionario", b =>
                {
                    b.HasOne("ElaArquitetura.Domain.Entities.Funcionario", null)
                        .WithMany()
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElaArquitetura.Domain.Entities.Projeto", null)
                        .WithMany()
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ElaArquitetura.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("ElaArquitetura.Domain.Entities.Funcionario", null)
                        .WithMany()
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ElaArquitetura.Domain.Entities.SubEtapa", b =>
                {
                    b.HasOne("ElaArquitetura.Domain.Entities.Etapa", null)
                        .WithMany()
                        .HasForeignKey("EtapaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
