@ElaArquitetura.Api_HostAddress = http://localhost:5164

POST {{ElaArquitetura.Api_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "admin@elaarquitetura.com.br",
  "senha": "Trocar123!"
}

###
